### PR TITLE
chore: update workflows

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Sets the Node.js engine to a minimum of 18.17.0.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Relates to #72

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
Maybe I'm reading the failure wrong, but doesn't moving to Node.js 18.17.0 fix the engine issue?

```
Run npm i -g npm@latest
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.2.5
npm ERR! notsup Not compatible with your version of node/npm: npm@10.2.5
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"8.19.[4](https://github.com/open-sauced/opengraph/actions/runs/7232618888/job/19765768242#step:4:5)","node":"v1[6](https://github.com/open-sauced/opengraph/actions/runs/7232618888/job/19765768242#step:4:7).20.2"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-12-19T00_11_4[7](https://github.com/open-sauced/opengraph/actions/runs/7232618888/job/19765768242#step:4:8)_407Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by bdougie** [comment]
> Maybe I'm reading the failure wrong, but doesn't moving to Node.js 18.17.0 fix the engine issue?

I would think so, however it seems like something is quite seeing the npm and node change. Does `npm run prebuild && npm run build` work locally?

**Comment by brandonroberts** [comment]
Maybe needs fixing here also https://github.com/open-sauced/opengraph/blob/beta/Dockerfile#L20

**Comment by bdougie** [comment]
> The workflow files need to be updated to use the `open-sauced/hot` workflows instead of `open-sauced/open-sauced` also
> 
> https://github.com/open-sauced/app/blob/beta/.github/workflows/compliance.yml#L15 https://github.com/open-sauced/app/blob/beta/.github/workflows/development.yml#L14C1-L14C1

This was helpful. I fix this PR with this - https://github.com/open-sauced/contributor.info/pull/16/commits/cd6bdc2d9abd2ed3e36b4788057e47bb780b21f0

**Comment by nickytonline** [comment]
Not sure why this fails still. All the workflows are updated, the docker file etc. 🫠

**Comment by brandonroberts** [comment]
The workflows in `opensauced/hot` are set to use node 18, which would conflict with us trying to use node 20 here

**Comment by brandonroberts** [comment]
We're using node 18 in the app https://github.com/open-sauced/app/blob/beta/.github/workflows/release.yml#L37

**Comment by nickytonline** [comment]
Il revert the node 20 upgrade then and just keep the updated workflows. Originally I thought it required Node 20, but it sounds like just updating workflows should be good.

**Review by bdougie — APPROVED** [review]

**Pull request merged**
