### PR TITLE
fix: sanitize highlight text

### PR DESCRIPTION
**Pull request by takanome-dev**
## Description
This PR fixes the issue with sanitizing the highlighted text. The code has been modified to ensure that the text is properly sanitized, preventing any potential security vulnerabilities. This improvement enhances the overall security of the application.

_Generated using [OpenSauced](https://opensauced.ai/)._

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #66 
## Mobile & Desktop Screenshots/Recordings

| Highlight | Before sanitization | After |
| ------ | ------ | ------ |
|  | 30-before | 30-escape|
|  | 17-before | 17-escape|

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by takanome-dev** [comment]
> I think we should be on the side of escaping everything and have it rendered as <em> and not em. I think people will recognize escaped HTML characters in the highlight text.
> _originally posted by @brandonroberts in https://github.com/open-sauced/opengraph/issues/66#issuecomment-1679086998_

Need to figure out how to do this

**Comment by brandonroberts** [comment]
Usually if the library sanitizes the HTML, it replaces all HTML entities with their equivalent, such as < becoming &lt;

If this one doesn't do that, we should find one that does.

**Comment by takanome-dev** [comment]
it does do it but if the sanitized text is passed to `satori`, it will treat it as html and it can break the layout (just guessing but I think that makes sense)
https://github.com/open-sauced/opengraph/blob/0fbbc75d62cf29eafbb4db48c940a0f90cb51d56/src/social-card/templates/highlight-card.template.ts#L20-L22

**Comment by brandonroberts** [comment]
@takanome-dev Ok, try escaping the HTML and see if that works. If so, we can go with that

**Comment by takanome-dev** [comment]
> @takanome-dev Ok, try escaping the HTML and see if that works. If so, we can go with that

Done :rocket:

**Comment by brandonroberts** [comment]
@takanome-dev instead of discarding them, is there no option to sanitize them as-is? So `<em>`, for example, is still displayed as `<em>` but not applied as HTML?

**Comment by takanome-dev** [comment]
That's what I have been trying to do. The `sanitize-html` that I have use can do it, but didn't find how to display html as text with satori.  Will dig more into that.

**Comment by brandonroberts** [comment]
> That's what I have been trying to do. The `sanitize-html` that I have use can do it, but didn't find how to display html as text with satori. Will dig more into that.

Ok. I see more how `sanitize-html` works, as it will allow certain tags and discard everything else. It may be the best path for now as its a proven solution, but let us know what you find.

**Comment by brandonroberts** [comment]
@takanome-dev did you find anymore alternatives here?

**Comment by takanome-dev** [comment]
> @takanome-dev did you find anymore alternatives here?

@brandonroberts sorry for the late response. Unfortunately, I didn't find any alternative or a way to display the html as a text in the generated og image.

**Comment by brandonroberts** [comment]
Ok cool. No problem

**Comment by nickytonline** [comment]
Closing this for now as there has been no movement since late August. Feel free to reopen @brandonroberts @takanome-dev if work resumes.

**Pull request closed without merging**
